### ISSUE TITLE
每一步操作都做了，但是依然为英文界面

### ISSUE THREAD

**Issue by ulitharid1709** [tinygrox/SunlessSeaCN#1]
开发者您好。照您在此项目介绍和说明.txt中的步骤，BepInEx确认安装了，游戏启动过了一次，BepInEx/Plugin下加了解压出的项目文件夹，BepInEx/Config/BepInEx.cfg改为了Type = Camera，但是仍然是英文界面。

**Comment by ulitharid1709** [comment]
准确的说，我在Github上下载的许多个X86版本的BepInEX在放入游戏根目录中并且启动游戏之后都无法生成Config文件，最后是迫不得已去N网上找了个打包好BepInEX以及Config文件的MOD覆盖进了根目录，同时删掉了LocalLow\Failbetter Games\Sunless Sea中的文件再次启动了一次游戏，但是仍然不行。

**Comment by ulitharid1709** [comment]
游戏版本是2.2.11.3212
N网上打包的BepInEX版本是5.4.17.0

**Comment by tinygrox** [comment]
问题不明确，是 steam 平台还是 epic 平台，如果是 Epic 平台，请截一张游戏根目录的图，我需要知道是 epic 是用 mono 还是 il2cpp。如果是 il2cpp，你可能需要使用 BepInEx 6，但不保证能正常用。

无法生成 Config 文件一般是 BepInex 未能运行导致的，游戏根目录应该会生成一个额外的由 doorstop 生成的错误日志文件，请将日志内容发上来。

现在你可先做以下尝试：

将 BepInEx 版本退回至 5.4.22 可下载我上传的这个： [BepInEx_x86_5.4.22.0.zip](https://github.com/user-attachments/files/17275073/BepInEx_x86_5.4.22.0.zip)

如不信任所上传文件，可去 BepInEx 原链接：[BepInEx 5.4.22](https://github.com/BepInEx/BepInEx/releases/tag/v5.4.22)

总之不要下载最新的 BepInEx，最新版本换了 Doorstop 4 导致某些系统下会有问题

然后解压如图：

![图片](https://github.com/user-attachments/assets/53c1b952-1d5b-4435-a1d7-25a81c2510df)

打开游戏后关闭，

下载本项目的zip文件，解压到BepInEx\plugins

![图片](https://github.com/user-attachments/assets/fec6e6aa-46a9-4a38-b313-9bcbab5a5a64)

**Comment by tinygrox** [comment]
问题未能复现且无后续跟进，issue 关闭

**Comment by ulitharid1709** [comment]
> 问题未能复现且无后续跟进，issue 关闭

开发者您好，我想说：“对不起，我是傻逼”。
Config文件无法生成的原因是我脑子昏了把BepInEX放到sunless_sea data 里去了，然后我居然没反应过来，给您添了不必要的打扰真是非常抱歉。
然后按照您所描述的流程又重新执行了一遍，仍是英文，遂卸载重装，这下成功了，非常感谢开发者您的耐心。
我再次为我的愚蠢向您道歉。
